version: '3'

services:
  api: # Node.js App
    container_name: finance-api
    build: .
    ports:
      - "3000:3000" # Expose API port
    environment: # Set ENV vars
     - NODE_ENV=local
     - ES_HOST=elasticsearch
     - PORT=3000
    volumes: # Attach local people data directory
      - ./people:/usr/src/app/people

  elasticsearch: # Elasticsearch Instance
    container_name: finance-search
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    volumes: # Persist ES data in seperate "esdata" volume
      - esdata:/usr/share/elasticsearch/data
    ports: # Expose Elasticsearch ports
      - "9300:9300"
      - "9200:9200"

volumes: # Define seperate volume for Elasticsearch data
  esdata:
