version: '3'
services:
  api:
    build: .
    command: npm run test
    ports:
      - "8080:8080"
    environment: # Set ENV vars
      - NODE_ENV=test
      - PORT=8080
      - MONGODB_URI=mongodb://db:27017/test-todos
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    depends_on:
      - db
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGODB_USER="test-user" 
      - MONGODB_PASS="test-pass"
